### ISSUE TITLE
Uploading an asset failed

### ISSUE THREAD

**Issue by Adivote** [imagitama/shiba-world#4]
When trying to upload a new asset at https://www.vrcarena.com/assets/create I get 2 errors:

```
breadcrumbs.js:76 FirebaseError: Missing or insufficient permissions.
    at new t (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:719105)
    at https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1040932
    at tr.<anonymous> (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1040133)
    at Ce (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1057877)
    at tr.r.dispatchEvent (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1058718)
    at ir.ua (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1088040)
    at Ln.r.Ga (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1085947)
    at Ct (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1064116)
    at bt (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1063517)
    at ht.r.Ka (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1065928)
    at ht.r.eb (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1065493)
    at Ce (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1057877)
    at xn.r.dispatchEvent (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1058718)
    at Pn (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1075112)
    at xn.r.$a (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1083147)
    at xn.r.Fa (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1083124)
    at XMLHttpRequest.r (https://www.vrcarena.com/static/js/2.8a58d83b.chunk.js:1:1783105)
(anonymous) @ 2.8a58d83b.chunk.js:1
breadcrumbs.js:76 TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at iterableToArrayLimit.js:8
    at r (slicedToArray.js:5)
    at index.jsx:40
    at _ (runtime.js:63)
    at Generator._invoke (runtime.js:282)
    at Generator.e.<computed> [as next] (runtime.js:116)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
(anonymous) @ 2.8a58d83b.chunk.js:1
```

**Comment by imagitama** [comment]
Fixed permissions. Thanks for the report!
